### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by soaressgabriel** [LabSid-USP/RUBEM#61]
- [x] From now on you can use RUBEM within the interactive shell or Python script:
```python
from rubem.core.model import Model

# load the model
model = Model.load("example.ini")
# run the model
model.run()
# check the result in the output folder
```
- [x] Create basic project organization structure;
- [x] Separate parts of code into related files;
- [x] Clean up unnecessary imports;
- [x] Clean up code that is commented out;
- [x] Remove unnecessary arguments from methods and functions;
- [x] Remove unnecessary attributes and variables;
- [x] Complete basic command line interface - CLI (continue at #48);
- [x] Add first model unit tests (continue at #62);
- [x] Isolate code files used internally from public library import;
- [x] Add model configuration file validation (including some type checking, continue at #2);
- [x] Add exceptions and handle errors;
- [x] Add logging and set default logging level to `INFO`;
